server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://transaction-db:3306/transactions
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring:
  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
